spring:
  data:
    mongodb:
      host: mongo_db
      database: capstone_db
      username: 'capstone'
      password: 'C@pst0n3'
      authentication-database: admin

logging:
  level:
    com.capstone.server: DEBUG
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG'

fixedRate:
  value: 2000

initialDelay:
  value: 10000

cron:
  expression:
    value: 0 */5 * ? * *

timezone: UTC